# Generated by Django 4.2.1 on 2023-06-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_review_user_alter_review_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='age_group',
            field=models.CharField(choices=[('A', '0-2 Years'), ('B', '3-4 Years'), ('C', '5-6 Years'), ('D', '7-9 Years'), ('E', '10-11 Years'), ('F', '12-13 Years')], default='A', max_length=1),
        ),
    ]
